/// <reference lib="webworker" />

import { build, files, version } from '$service-worker'

const worker = self
const FILES = `cache-${version}`

// `build` is an array of all the files generated by the bundler,
// `files` is an array of everything in the `static` directory
const toCache = build.concat(files)
const staticAssets = new Set(toCache)

worker.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(FILES)
      .then((cache) => cache.addAll(toCache))
      .then(() => {
        worker.skipWaiting()
      })
  )
})

worker.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then(async (keys) => {
      // delete old caches
      for (const key of keys) {
        if (key !== FILES) await caches.delete(key)
      }

      worker.clients.claim()
    })
  )
})

/**
 * Fetch a page from the network and keep a copy so it can be served offline.
 * Only successful responses are kept - a cached 404 or 500 would otherwise be
 * re-served on the next offline visit as if it were the page.
 */
async function fetchAndCache (request) {
  const cache = await caches.open(`offline${version}`)

  try {
    const response = await fetch(request)
    if (response.ok) cache.put(request, response.clone())
    return response
  } catch (err) {
    const response = await cache.match(request)
    if (response) return response

    throw err
  }
}

worker.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET' || event.request.headers.has('range')) return

  const url = new URL(event.request.url)

  // don't try to handle e.g. data: URIs
  const isHttp = url.protocol.startsWith('http')
  const isDevServerRequest =
    url.hostname === self.location.hostname && url.port !== self.location.port
  const isStaticAsset = url.host === self.location.host && staticAssets.has(url.pathname)
  const skipBecauseUncached = event.request.cache === 'only-if-cached' && !isStaticAsset

  if (!isHttp || isDevServerRequest || skipBecauseUncached) return

  if (isStaticAsset) {
    // always serve static files and bundler-generated assets from cache.
    event.respondWith(caches.match(event.request).then(cached => cached || fetch(event.request)))
    return
  }

  // Only page navigations are cached for offline use. Everything else - the
  // /api/collections reads behind every page, badge images, cross-origin
  // media thumbnails - goes straight to the network: caching those served
  // stale data and error bodies back to agents who were merely offline for
  // a moment.
  if (event.request.mode === 'navigate') {
    event.respondWith(fetchAndCache(event.request))
  }
})
